defaults:
  - defaults
  - mode: adversarial_erasing_cancer

data:
  directory: data/breast_cancer
  original_width: 480
  original_height: 480

transforms:
  resize_width: 480
  resize_height: 480

  normalization:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

learning_rate: 1e-4
batch_size: 32
